# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: required
cache: packages

r:
#  - oldrel
  - release
  - devel

r_github_packages:
  - cran/survival
  
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  